# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
branches:
    only:
        - master
language: r
#compiler: clang
#compiler: gcc
sudo: true
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
            - llvm-toolchain-precise-3.7
            - boost-latest
        packages:
            - cmake
            - libboost1.55-dev
            - libboost-filesystem1.55-dev
            - libboost-locale1.55-dev
            - libssl-dev
            - libpng-dev
            - libjpeg-dev
            - clang-3.7
            - g++-5
            - gcc-5
            
            
#env: CMAKE_BUILD_TYPE=RELEASE

os:
  - linux

compiler:
  - gcc

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"


before_install:
    - sudo apt-get update -qq
    #- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    #- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
#script:
#    - mkdir build && cd build && cmake .. && cmake --build . 

r_packages:
  - devtools
  - roxygen2
  - testthat
  - Rcpp
  - RcppArmadillo
  - covr
  - Matrix
  - R6
  - data.table
  - utils
  - BH
  - knitr
  - rmarkdown
  

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = c("R/RcppExports.R", "src/RcppExports.cpp"), quiet = FALSE)'

notifications:
  email:
    on_success: change
    on_failure: change
