# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true

branches:
    only:
        - master
os:
  - linux
  #- osx


compiler:
  - gcc
  #- clang

env:
  global:
    - CMAKE_BUILD_TYPE=RELEASE
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"


before_install:
  #---------------------------------------------------------------------- Installation on Linux
  - sudo apt-get install libboost-all-dev
  - sudo apt-get update -qq
  - sudo apt-get install libarmadillo-dev libopenblas-dev libblas-dev libarpack++2-dev liblapack-dev
  - sudo apt-get install libgfortran3 gfortran
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so
  - sudo apt-get install r-base-dev
  - sudo apt-get update
  #---------------------------------------------------------------------- Installation on Macintosh [ gives : clang: error: unsupported option '-fopenmp' ( configuration with openmp is required ) ]
  #- brew update
  #- brew install llvm
  #- echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
  #- echo 'export LDFLAGS = "-L/usr/local/opt/llvm/lib"' >> ~/.bash_profile
  #- echo 'export CPPFLAGS = "-I/usr/local/opt/llvm/include"' >> ~/.bash_profile
  #- brew install libomp
  #---------------------------------------------------------------------- 

r_packages:
  - devtools
  - roxygen2
  - testthat
  - Rcpp
  - RcppArmadillo
  - covr
  - Matrix
  - R6
  - data.table
  - utils
